### PR TITLE
Move the resources directory up one level

### PR DESCRIPTION
**Pull request by gbrixey**
This is to fix an SPM issue in Xcode 12.5. It seems SPM doesn't want there to be any directories at the same level as the umbrella header `CTAssetsPickerController.h`

### CODE REVIEW

**Comment by veeamd** [comment]
If the Resources folder moved out of CTAssetsPickerController folder, with the current target definition
```
.target(name: "CTAssetsPickerController",
                dependencies: ["PureLayout"],
                path: "CTAssetsPickerController",
                publicHeadersPath: "")
```
and given `path: "CTAssetsPickerController"`, would it be able to find the Resources?

**Comment by veeamd** [comment]
if adding an `include` umbrella folder works in the other repo, maybe give it try here as well.

**Comment by gbrixey** [comment]
> If the Resources folder moved out of CTAssetsPickerController folder, with the current target definition... and given path: "CTAssetsPickerController", would it be able to find the Resources?

It looks like the resources aren't being included, either in this branch or in the master branch. 😕  I took a look at the current app store version, and it seems none of the images are appearing, e.g. the checkmark icon when an image is selected from a photo album.

**Comment by gbrixey** [comment]
I'll close this PR in favor of #5

**Pull request closed without merging**
